version: "3.8"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: clinic_db

  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - clinic-network
    environment:
      NODE_ENV: development
      DB_HOST: host.docker.internal
      DB_NAME: clinic_db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_PORT: 5432

networks:
  clinic-network:
    driver: bridge

volumes:
  data:
    driver: local
